steps:
    check:
        image: runmymind/docker-android-sdk:latest
        when:
          branch: main
          event: [push, pull_request]
        commands:
          - ./gradlew assembleRelease ktlintCheck --stacktrace

    build:
        image: runmymind/docker-android-sdk:latest
        when:
          branch: main
          event: tag
        commands:
          - export RELEASE_STORE_FILE=$PWD/release-key.jks
          - echo $RELEASE_KEY | base64 -d > $RELEASE_STORE_FILE
          - ./gradlew -Psign assembleRelease --stacktrace
          - mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/fcm-distributor.apk
        environment:
          RELEASE_KEY_ALIAS: unifiedpush
          RELEASE_KEY:
            from_secret: release_key
          RELEASE_STORE_PASSWORD:
            from_secret: release_store_password
          RELEASE_KEY_PASSWORD:
            from_secret: release_key_password

    upload:
        image: codeberg.org/s1m/woodpecker-upload:latest
        when:
            branch: main
            event: tag
        settings:
            token:
                from_secret: codeberg_token
            file: app/build/outputs/apk/fcm-distributor.apk
            fastlane: true

